name: WellWorld
main: me.daddychurchill.WellWorld.WellWorld
version: 0.7
load: startup
author: DaddyChurchill
commands:
  wellworld:
    description: Sends you to the WellWorld.
    usage: /wellworld