name: WellWorld
main: me.daddychurchill.WellWorld.WellWorld
version: 0.81
load: startup
author: DaddyChurchill
commands:
  wellworld:
    description: Sends you to the WellWorld or back to "World".
    usage: /wellworld [leave]
