name: WellWorld
main: me.daddychurchill.WellWorld.WellWorld
version: 1.13
load: startup
api-version: 1.13
author: DaddyChurchill
commands:
  wellworld:
    description: Sends you to the WellWorld.
    usage: /wellworld
